# Generated by Django 2.1 on 2018-08-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player to Move'), ('W', 'First Player Wins'), ('S', 'Second Player to Move'), ('D', 'Draw'), ('L', 'Second Player Wins')], default='F', max_length=1),
        ),
    ]
